### ISSUE TITLE
Your documentation sucks

### ISSUE THREAD

**Issue by Revadike** [antigravities/libbarter#1]
and you suck

**Comment by antigravities** [comment]
documentation Will Come™️ when the API is more stable

**Comment by antigravities** [comment]
I've added [some documentation](https://github.com/antigravities/libbarter/wiki). Still working on it.

**Comment by antigravities** [comment]
Everything should be documented.

**Comment by Revadike** [comment]
Barter API is now also documented:
https://github.com/bartervg/barter.vg/wiki
